

use_cuda: True
gpus: '0'
max_epochs: 200
map_type: segmentation
save_interval: 1

num_sample_cvae: 1
num_sample_cell: 20

weight_dir: weights
result_dir: result
visualization_dir: vis
data_dir: data
manual_batch_size: 32

dataset_name: SDD
batch_size: 64
clip_length: 20
obs_length: 8
future_length: 12
traj_norm: 1.

resize_factor: 4.
ori_global_size: 1200
global_size: 300
global_anchor_size: 15
global_step: 80
ori_local_size: 60
local_size: 15
local_anchor_size: 3
local_step: 20

models:
    feat:
        traj_shift_emb_dims: [3,64,32,64]
        traj_ref_emb_dims: [3,32,16,32]
        traj_vel_emb_dims: [2,32,16,32]
        scene_dims: [7,16,32,32,64,64,128,128]

        n_layers: 2
        n_heads: 8
        dropout: 0. 

        encoder_att_dims: [256,128]
        encoder_ffn_dims: [256,128]

    goal:
        gt_emb_dims: [3,64,32,64]
        encoder_dims: [320,128,256,128]
        decoder_dims: [320,128,32,3]
        
        latent_dim: 64

        kld_weight: 40.0
        recon_conf_weight: 400.0
        recon_offset_weight: 100.0

        n_samples: 20

    traj:
        n_layers: 2
        n_heads: 8
        dropout: 0. 

        decoder_att_dims: [256,128]
        decoder_ffn_dims: [256,128]

        prediction_dims: [512,128,32,3]

        conf_weight: 20.0
        offset_weight: 2.0

    learning_rate: 0.0001
